name: Public repos
"on":
  push:

jobs:
  test:
    strategy:
      # run each one to completion
      fail-fast: false
      matrix:
        repository:
          - https://github.com/pantsbuild/example-python
          - https://github.com/pantsbuild/example-visibility
          - https://github.com/pantsbuild/example-django
          - https://github.com/pantsbuild/example-adhoc
          - https://github.com/pantsbuild/example-jvm
          - https://github.com/pantsbuild/example-golang
          - https://github.com/pantsbuild/example-kotlin
          - https://github.com/pantsbuild/example-docker
          - https://github.com/pantsbuild/example-codegen

          # - https://github.com/StackStorm/st2
          # - https://github.com/lablup/backend.ai
          # - https://github.com/Ars-Linguistica/mlconjug3
          # - https://github.com/mitodl/ol-infrastructure
          # - https://github.com/naccdata/flywheel-gear-extensions
          # - https://github.com/OpenSaMD/OpenSaMD

    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.7
            3.8
            3.9
            3.10

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5

      - name: "Pants on"
        run: |
          # FIXME: save the script somewhere
          curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash -
          echo "$HOME/bin" | tee -a $GITHUB_PATH

      - name: "Check out"
        run: |
          git clone --depth=1 ${{ matrix.repository }} repo
          cd repo
          pwd
          git rev-parse HEAD

      - run: |
          pants version
        working-directory: repo
      - run: |
          pants tailor --check update-build-files --check ::
        working-directory: repo
      - run: |
          pants lint check ::
        working-directory: repo
      - run: |
          pants test ::
        working-directory: repo
      - run: |
          pants package ::
        working-directory: repo
