name: Public repos
"on":
  push:

jobs:
  test:
    strategy:
      # run each one to completion
      fail-fast: false
      matrix:
        repository:
          # pants' examples
          - pantsbuild/example-python
          - pantsbuild/example-visibility
          - pantsbuild/example-django
          - pantsbuild/example-adhoc
          - pantsbuild/example-jvm
          - pantsbuild/example-golang
          - pantsbuild/example-kotlin
          - pantsbuild/example-docker
          - pantsbuild/example-codegen
          # public repos (just from a basic search for path:pants.toml on github)
          - StackStorm/st2
          - lablup/backend.ai
          - Ars-Linguistica/mlconjug3
          - mitodl/ol-infrastructure
          - naccdata/flywheel-gear-extensions
          - OpenSaMD/OpenSaMD
        pants_version:
          # repo's default version
          # FIXME: https://github.com/pantsbuild/scie-pants/pull/190
          # - ""
          # try latest/future versions
          - 2.15.0
          - 2.16.0rc3
          - 2.17.0a1

    runs-on: ubuntu-22.04
    env:
      PANTS_VERSION: ${{ matrix.pants_version }}
      # for example-docker:
      DYNAMIC_TAG: dynamic-tag-here
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          # 3.9.15 is specifically required by OpenSaMD/OpenSaMD
          python-version: |
            3.7
            3.8
            3.9.15
            3.10

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5

      # for example-adhoc
      - if: runner.os == 'Linux'
        name: Download Apache `thrift` binary (Linux)
        run: 'mkdir -p "${HOME}/.thrift"

          curl --fail -L https://binaries.pantsbuild.org/bin/thrift/linux/x86_64/0.15.0/thrift -o "${HOME}/.thrift/thrift"

          chmod +x "${HOME}/.thrift/thrift"

          echo "${HOME}/.thrift" >> $GITHUB_PATH

          '

      - name: "Pants on"
        run: |
          # FIXME: save the script somewhere
          curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash -
          echo "$HOME/bin" | tee -a $GITHUB_PATH

      - name: "Check out"
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repository }}

      - run: |
          if [[ -f pants.ci.toml ]]; then
            echo "PANTS_CONFIG_FILES=pants.ci.toml" | tee -a $GITHUB_ENV
          fi
          # for lablup/backend.ai
          mkdir .tmp

      - run: |
          pants version
      # several repos don't pass this
      # - run: |
      #     pants tailor --check update-build-files --check ::
      - run: |
          pants lint check ::
      - run: |
          pants test ::
      - run: |
          pants package ::
